// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	sysUser "docs/app/sys_user_center/cmd/api/internal/handler/sysUser"
	"docs/app/sys_user_center/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// user login
				Method:  http.MethodPost,
				Path:    "/sysuser/login",
				Handler: sysUser.LoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/sysusercenter/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// get user info
				Method:  http.MethodGet,
				Path:    "/sysuser/detail",
				Handler: sysUser.DetailHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/sysusercenter/v1"),
	)
}
