// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: welcomerpc.proto

package welcomerpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Welcomerpc_Ping_FullMethodName = "/welcomerpc.Welcomerpc/Ping"
)

// WelcomerpcClient is the client API for Welcomerpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WelcomerpcClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type welcomerpcClient struct {
	cc grpc.ClientConnInterface
}

func NewWelcomerpcClient(cc grpc.ClientConnInterface) WelcomerpcClient {
	return &welcomerpcClient{cc}
}

func (c *welcomerpcClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, Welcomerpc_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WelcomerpcServer is the server API for Welcomerpc service.
// All implementations must embed UnimplementedWelcomerpcServer
// for forward compatibility.
type WelcomerpcServer interface {
	Ping(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedWelcomerpcServer()
}

// UnimplementedWelcomerpcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWelcomerpcServer struct{}

func (UnimplementedWelcomerpcServer) Ping(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedWelcomerpcServer) mustEmbedUnimplementedWelcomerpcServer() {}
func (UnimplementedWelcomerpcServer) testEmbeddedByValue()                    {}

// UnsafeWelcomerpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WelcomerpcServer will
// result in compilation errors.
type UnsafeWelcomerpcServer interface {
	mustEmbedUnimplementedWelcomerpcServer()
}

func RegisterWelcomerpcServer(s grpc.ServiceRegistrar, srv WelcomerpcServer) {
	// If the following call pancis, it indicates UnimplementedWelcomerpcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Welcomerpc_ServiceDesc, srv)
}

func _Welcomerpc_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WelcomerpcServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Welcomerpc_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WelcomerpcServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Welcomerpc_ServiceDesc is the grpc.ServiceDesc for Welcomerpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Welcomerpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "welcomerpc.Welcomerpc",
	HandlerType: (*WelcomerpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Welcomerpc_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "welcomerpc.proto",
}
