// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: welcomerpc.proto

package welcomerpcclient

import (
	"context"

	"docs/welcomerpc/welcomerpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = welcomerpc.Request
	Response = welcomerpc.Response

	Welcomerpc interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultWelcomerpc struct {
		cli zrpc.Client
	}
)

func NewWelcomerpc(cli zrpc.Client) Welcomerpc {
	return &defaultWelcomerpc{
		cli: cli,
	}
}

func (m *defaultWelcomerpc) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := welcomerpc.NewWelcomerpcClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
