// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: welcomerpc.proto

package server

import (
	"context"

	"docs/welcomerpc/internal/logic"
	"docs/welcomerpc/internal/svc"
	"docs/welcomerpc/welcomerpc"
)

type WelcomerpcServer struct {
	svcCtx *svc.ServiceContext
	welcomerpc.UnimplementedWelcomerpcServer
}

func NewWelcomerpcServer(svcCtx *svc.ServiceContext) *WelcomerpcServer {
	return &WelcomerpcServer{
		svcCtx: svcCtx,
	}
}

func (s *WelcomerpcServer) Ping(ctx context.Context, in *welcomerpc.Request) (*welcomerpc.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
